/*You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

*/

//Time Complexity -- O(n)

class Solution {
public:
    char findTheDifference(string s, string t) {
        int n=t.size();
        unordered_map<char,int>m1;
        for(int i=0;i<n-1;i++){
            m1[s[i]]++;
        }
        unordered_map<char,int>m2;
        for(int i=0;i<n;i++){
            m2[t[i]]++;
        }
        char ch;
        for(auto i:m2){
            if(m1.count(i.first)==0||i.second!=m1[i.first]){
                ch = i.first;
                break;
            }
        }
        return ch;
    }
};
